### ISSUE TITLE
azkaban任务调度框架关于job logs中中文乱码的问题，如何解决？

### ISSUE THREAD

**Issue by shengjianjia** [V-I-C-T-O-R/V-I-C-T-O-R.github.io#1]
如题

**Comment by V-I-C-T-O-R** [comment]
@shengjianjia 请看[这里](https://v-i-c-t-o-r.github.io/2017/12/29/Azkaban%E4%B8%AD%E6%96%87%E4%B9%B1%E7%A0%81.html)，对应改代码
