### ISSUE TITLE
关于Mybatis解析Node成完整Sql希望获取帮助

### ISSUE THREAD

**Issue by kunmeng** [V-I-C-T-O-R/V-I-C-T-O-R.github.io#3]
Mybatis解析Node成完整Sql
https://v-i-c-t-o-r.github.io/2018/02/11/Mybatis%E4%B9%8Bsql%E8%A7%A3%E6%9E%90.html
目前，碰到 需要再后台传递动态的sql，支持if 等标签
我看过您写的如上文章，对我有帮助，希望寻求帮助合作，有重金答谢。

**Comment by V-I-C-T-O-R** [comment]
@kunmeng 你好，请问有什么可以帮到你?你发布的链接是18年的时候做的相关工作，有些时日了
